# Generated by Django 3.2.8 on 2024-02-27 11:20

import core.utils.units
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gridx', '0008_auto_20230803_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('uid', models.CharField(default=core.utils.units.genserial, max_length=10)),
                ('meter_number', models.CharField(db_index=True, max_length=50)),
                ('device_pk', models.CharField(db_index=True, max_length=5)),
                ('voltage_level', models.CharField(blank=True, max_length=10, null=True)),
                ('band', models.CharField(max_length=10)),
                ('commissioned_date', models.CharField(help_text='Date time in Unix Format', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('feeder_11', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gridx.feeder')),
                ('feeder_33', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gridx.feeder')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('injection_substation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gridx.station')),
                ('transmission_station', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gridx.transmissionstation')),
            ],
            options={
                'verbose_name': 'historical AMI Meter Device',
                'verbose_name_plural': 'historical AMI Meter Devices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=core.utils.units.genserial, max_length=10)),
                ('meter_number', models.CharField(max_length=50, unique=True)),
                ('device_pk', models.CharField(max_length=5, unique=True)),
                ('voltage_level', models.CharField(blank=True, max_length=10, null=True)),
                ('band', models.CharField(max_length=10)),
                ('commissioned_date', models.CharField(help_text='Date time in Unix Format', max_length=20)),
                ('feeder_11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_11', to='gridx.feeder')),
                ('feeder_33', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_33', to='gridx.feeder')),
                ('injection_substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ami_devices', to='gridx.station')),
                ('transmission_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ami_devices', to='gridx.transmissionstation')),
            ],
            options={
                'verbose_name': 'AMI Meter Device',
                'verbose_name_plural': 'AMI Meter Devices',
                'ordering': ('-updated',),
            },
        ),
    ]
