# Generated by Django 3.2.8 on 2024-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='band',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='band',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
