# Generated by Django 3.2.8 on 2024-02-27 12:38

import core.utils.units
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_auto_20230316_1140'),
        ('ami', '0002_auto_20240227_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDeviceReading',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('uid', models.CharField(default=core.utils.units.getUniqueId, max_length=10)),
                ('reading_timestamp', models.CharField(help_text='Date time in Unix Format', max_length=20)),
                ('VA', models.FloatField(default=0.0)),
                ('VB', models.FloatField(default=0.0)),
                ('VC', models.FloatField(default=0.0)),
                ('IA', models.FloatField(default=0.0)),
                ('IB', models.FloatField(default=0.0)),
                ('IC', models.FloatField(default=0.0)),
                ('PF', models.FloatField(default=0.0)),
                ('MW', models.FloatField(default=0.0)),
                ('MW2', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=4)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ami.device')),
                ('record_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'historical AMI Meter Reading',
                'verbose_name_plural': 'historical AMI Meter Readings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=core.utils.units.getUniqueId, max_length=10)),
                ('reading_timestamp', models.CharField(help_text='Date time in Unix Format', max_length=20)),
                ('VA', models.FloatField(default=0.0)),
                ('VB', models.FloatField(default=0.0)),
                ('VC', models.FloatField(default=0.0)),
                ('IA', models.FloatField(default=0.0)),
                ('IB', models.FloatField(default=0.0)),
                ('IC', models.FloatField(default=0.0)),
                ('PF', models.FloatField(default=0.0)),
                ('MW', models.FloatField(default=0.0)),
                ('MW2', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=4)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='ami.device')),
                ('record_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ami_meter_readings', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'AMI Meter Reading',
                'verbose_name_plural': 'AMI Meter Readings',
                'ordering': ('-updated',),
            },
        ),
    ]
