# Generated by Django 3.2.8 on 2021-12-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_lga_state'),
        ('gridx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltransformer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Transformer'},
        ),
        migrations.AlterModelOptions(
            name='transformer',
            options={'ordering': ['-updated'], 'verbose_name': 'Transformer', 'verbose_name_plural': 'Transformers'},
        ),
        migrations.AddField(
            model_name='feeder',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feeders', to='location.region'),
        ),
        migrations.AddField(
            model_name='historicalfeeder',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.region'),
        ),
    ]
