# Generated by Django 3.2.8 on 2021-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridx', '0002_auto_20211223_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransformer',
            name='bookcode_1',
            field=models.CharField(default='00/00/00', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltransformer',
            name='bookcode_2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransformer',
            name='bookcode_3',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='bookcode_1',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformer',
            name='bookcode_2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='bookcode_3',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
