# Generated by Django 3.2.8 on 2022-01-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridx', '0003_auto_20211229_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeeder',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeeder',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeeder',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransformer',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransformer',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransformer',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
