# Generated by Django 3.2.8 on 2022-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridx', '0005_auto_20220107_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='billing_postpaid_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='billing_prepaid_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeeder',
            name='billing_postpaid_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeeder',
            name='billing_prepaid_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
