# Generated by Django 3.2.8 on 2022-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridx', '0006_auto_20220109_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfeeder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Feeder', 'verbose_name_plural': 'historical Feeders'},
        ),
        migrations.AlterModelOptions(
            name='historicaltransformer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Transformer', 'verbose_name_plural': 'historical Transformers'},
        ),
        migrations.AlterField(
            model_name='historicalfeeder',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltransformer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
