# Generated by Django 3.2.8 on 2023-08-03 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20220927_1051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gridx', '0007_auto_20220927_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeder',
            options={'ordering': ('-updated',), 'verbose_name': 'Feeder', 'verbose_name_plural': 'Feeders'},
        ),
        migrations.AlterModelOptions(
            name='transformer',
            options={'ordering': ('-updated',), 'verbose_name': 'Transformer', 'verbose_name_plural': 'Transformers'},
        ),
        migrations.CreateModel(
            name='TransmissionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('cavti_id', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmission_stations', to='location.state')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('capacity', models.CharField(choices=[('11kva', '11KV'), ('33kva', '33KV')], default='11kva', max_length=5)),
                ('cavti_id', models.PositiveIntegerField(blank=True, null=True)),
                ('billing_prepaid_id', models.CharField(blank=True, max_length=5, null=True)),
                ('billing_postpaid_id', models.CharField(blank=True, max_length=5, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='location.region')),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='gridx.transmissionstation')),
            ],
            options={
                'verbose_name': 'Injection Substation',
                'verbose_name_plural': 'Injection Substations',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransmissionStation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('cavti_id', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.state')),
            ],
            options={
                'verbose_name': 'historical transmission station',
                'verbose_name_plural': 'historical transmission stations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('capacity', models.CharField(choices=[('11kva', '11KV'), ('33kva', '33KV')], default='11kva', max_length=5)),
                ('cavti_id', models.PositiveIntegerField(blank=True, null=True)),
                ('billing_prepaid_id', models.CharField(blank=True, max_length=5, null=True)),
                ('billing_postpaid_id', models.CharField(blank=True, max_length=5, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.region')),
                ('transmission', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gridx.transmissionstation')),
            ],
            options={
                'verbose_name': 'historical Injection Substation',
                'verbose_name_plural': 'historical Injection Substations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
