from django.urls import path
from .views import (
    StaffLoginObtainAuthToken,
    CustomerLoginObtainAuthToken,
    VendorLoginObtainAuthToken,
    ContractorLoginObtainAuthToken,
    ComboLoginObtainAuthToken,
    CreateStaffAccountAPIView,
    CreateCustomerAccountAPIView,
    CreateVendorAccountAPIView,
    CreateContractorProfileAccountAPIView,
    ChangePassword,
    ResetPassword,
    StaffUserProfileListAPIView,
    StaffUserProfileSearchAPIView,
    StaffUserProfileDetailsAPIView,
    StaffUserProfileUpdateAPIView,
    StaffUserProfileDeleteAPIView,
    CustomerProfileListAPIView,
    CustomerProfileSearchAPIView,
    CustomerProfileDetailsAPIView,
    CustomerUserProfileUpdateAPIView,
    CustomerProfileDeleteAPIView,
    VendorProfileListAPIView,
    VendorProfileSearchAPIView,
    VendorProfileDetailsAPIView,
    VendorProfileUpdateAPIView,
    VendorProfileDeleteAPIView,
    ContractorProfileListAPIView,
    ContractorProfileDetailsAPIView,
    ContractorProfileUpdateAPIView,
    ContractorProfileSearchAPIView,
    ContractorProfileDeleteAPIView,
    ProfileStatsDashboard,
    
)

urlpatterns = [
    path("jwt/staff/", StaffLoginObtainAuthToken.as_view()),
    path("jwt/customer/", CustomerLoginObtainAuthToken.as_view()),
    path("jwt/vendor/", VendorLoginObtainAuthToken.as_view()),
    path("jwt/contractor/", ContractorLoginObtainAuthToken.as_view()),
    path("jwt/combo/", ComboLoginObtainAuthToken.as_view()),
    path("create-user/staff/", CreateStaffAccountAPIView.as_view()),
    path("create-user/customer/", CreateCustomerAccountAPIView.as_view()),
    path("create-user/vendor/", CreateVendorAccountAPIView.as_view()),
    path("create-user/contractor/", CreateContractorProfileAccountAPIView.as_view()),
    path("change-password/", ChangePassword.as_view()),
    path("reset-password/", ResetPassword.as_view()),
    path("profile/staff/list/", StaffUserProfileListAPIView.as_view()),
    path("profile/staff/search/", StaffUserProfileSearchAPIView.as_view()),
    path("profile/staff/details/<pk>/", StaffUserProfileDetailsAPIView.as_view()),
    path("profile/staff/update/<pk>/", StaffUserProfileUpdateAPIView.as_view()),
    path("profile/staff/delete/<pk>/", StaffUserProfileDeleteAPIView.as_view()),
    path("profile/customer/list/", CustomerProfileListAPIView.as_view()),
    path("profile/customer/search/", CustomerProfileSearchAPIView.as_view()),
    path("profile/customer/details/<pk>/",
         CustomerProfileDetailsAPIView.as_view()),
    path("profile/customer/update/<pk>/",
         CustomerUserProfileUpdateAPIView.as_view()),
    path("profile/customer/delete/<pk>/",
         CustomerProfileDeleteAPIView.as_view()),
    path("profile/vendor/list/", VendorProfileListAPIView.as_view()),
    path("profile/vendor/search/", VendorProfileSearchAPIView.as_view()),
    path("profile/vendor/details/<pk>/", VendorProfileDetailsAPIView.as_view()),
    path("profile/vendor/update/<pk>/", VendorProfileUpdateAPIView.as_view()),
    path("profile/vendor/delete/<pk>/", VendorProfileDeleteAPIView.as_view()),
    #
    path("profile/contractor/list/", ContractorProfileListAPIView.as_view()),
    path("profile/contractor/search/", ContractorProfileSearchAPIView.as_view()),
    path("profile/contractor/details/<pk>/",
         ContractorProfileDetailsAPIView.as_view()),
    path("profile/contractor/update/<pk>/", ContractorProfileUpdateAPIView.as_view()),
    path("profile/contractor/delete/<pk>/", ContractorProfileDeleteAPIView.as_view()),
    #
    path("profile/stats/dashboard/", ProfileStatsDashboard.as_view()),
]
