# Generated by Django 3.2.7 on 2021-09-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lga',
            options={'ordering': ['title', 'state'], 'verbose_name': 'LGA', 'verbose_name_plural': 'LGAs'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['title'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
    ]
