# Generated by Django 3.2.8 on 2021-12-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_csp_historicalcsp_historicalregion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='location.state'),
        ),
    ]
