# Generated by Django 3.2.8 on 2022-01-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_lga_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='csp',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csp',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csp',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcsp',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcsp',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcsp',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalregion',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalregion',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalregion',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='billing_postpaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='billing_prepaid_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='cavti_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
