# Generated by Django 3.2.8 on 2022-01-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20220104_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csp',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.lga'),
        ),
    ]
