# Generated by Django 3.2.8 on 2022-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20220104_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcsp',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical CSP', 'verbose_name_plural': 'historical CSPs'},
        ),
        migrations.AlterModelOptions(
            name='historicallga',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical LGA', 'verbose_name_plural': 'historical LGAs'},
        ),
        migrations.AlterModelOptions(
            name='historicalregion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Region', 'verbose_name_plural': 'historical Regions'},
        ),
        migrations.AlterModelOptions(
            name='historicalstate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical State', 'verbose_name_plural': 'historical States'},
        ),
        migrations.AlterField(
            model_name='historicalcsp',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallga',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
