# Generated by Django 3.2.8 on 2021-10-07 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
