# Generated by Django 3.2.8 on 2021-12-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_historicalvendorprofile_vendorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
