# Generated by Django 3.2.8 on 2021-12-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_lga_state'),
        ('accounts', '0007_auto_20211222_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.region'),
        ),
    ]
