# Generated by Django 3.2.8 on 2022-01-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20220104_1551'),
        ('accounts', '0008_alter_customerprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='csp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.csp'),
        ),
    ]
