# Generated by Django 3.2.8 on 2022-01-19 14:00

import core.utils.units
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220119_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpasswordresettokens',
            name='token',
            field=models.CharField(db_index=True, default=core.utils.units.genserial, max_length=10),
        ),
        migrations.AlterField(
            model_name='passwordresettokens',
            name='token',
            field=models.CharField(default=core.utils.units.genserial, max_length=10, unique=True),
        ),
    ]
