# Generated by Django 3.2.8 on 2022-02-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220119_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpasswordresettokens',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresettokens',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
