# Generated by Django 3.2.8 on 2022-02-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220201_1339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passwordresettokens',
            unique_together=set(),
        ),
    ]
