# Generated by Django 3.2.8 on 2022-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_passwordresettokens_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcustomerprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Customer Profile', 'verbose_name_plural': 'historical Customer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='historicalpasswordresettokens',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Password Reset Token', 'verbose_name_plural': 'historical Passwords Reset Tokens'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Staff User Profile', 'verbose_name_plural': 'historical Staff User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='historicalusertype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical User Type', 'verbose_name_plural': 'historical User Types'},
        ),
        migrations.AlterModelOptions(
            name='historicalvendorprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vendor User Profile', 'verbose_name_plural': 'historical Vendors Users Profiles'},
        ),
        migrations.AlterField(
            model_name='historicalcustomerprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpasswordresettokens',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalusertype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvendorprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
