# Generated by Django 3.2.8 on 2022-12-23 10:36

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20221220_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='nemsa_licence',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(14), accounts.models.validate_contractor_nimsa]),
        ),
        migrations.AlterField(
            model_name='historicalcontractorprofile',
            name='nemsa_licence',
            field=models.CharField(db_index=True, max_length=16, validators=[django.core.validators.MinLengthValidator(14), accounts.models.validate_contractor_nimsa]),
        ),
    ]
