# Generated by Django 3.2.8 on 2022-12-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20221223_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontractorprofile',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
