# Generated by Django 3.2.8 on 2023-03-16 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20230313_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='company_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='licence_expire_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 10, 40, 17, 321000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontractorprofile',
            name='company_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontractorprofile',
            name='licence_expire_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 10, 40, 31, 355339, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
