# Generated by Django 3.2.8 on 2022-10-13 15:25

import core.utils.core_routings
import core.utils.units
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_auto_20221012_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MDMeterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=core.utils.units.genserial, max_length=10)),
                ('company_name', models.CharField(max_length=50)),
                ('company_registration_no', models.CharField(max_length=10)),
                ('company_phone', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(choices=[('KANO', 'KANO'), ('KASTINA', 'KASTINA'), ('JIGAWA', 'JIGAWA')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True, validators=[core.utils.core_routings.checkAccountNumber])),
                ('meter_number', models.CharField(blank=True, max_length=15, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('awaiting_inspection', 'Awaiting Inspection'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], max_length=50)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='md_meter_applications', to='accounts.contractorprofile')),
            ],
            options={
                'verbose_name': 'MD Meter Application',
                'verbose_name_plural': 'MD Meters Applications',
                'ordering': ['-updated', 'contractor', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMDMeterApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('uid', models.CharField(default=core.utils.units.genserial, max_length=10)),
                ('company_name', models.CharField(max_length=50)),
                ('company_registration_no', models.CharField(max_length=10)),
                ('company_phone', models.CharField(max_length=50)),
                ('company_email', models.EmailField(db_index=True, max_length=254)),
                ('state', models.CharField(choices=[('KANO', 'KANO'), ('KASTINA', 'KASTINA'), ('JIGAWA', 'JIGAWA')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True, validators=[core.utils.core_routings.checkAccountNumber])),
                ('meter_number', models.CharField(blank=True, max_length=15, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('awaiting_inspection', 'Awaiting Inspection'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contractor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.contractorprofile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical MD Meter Application',
                'verbose_name_plural': 'historical MD Meters Applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
