# Generated by Django 3.2.8 on 2022-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmdmeterapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('awaiting_inspection', 'Awaiting Inspection'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], default='awaiting_approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='mdmeterapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('awaiting_inspection', 'Awaiting Inspection'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], default='awaiting_approval', max_length=50),
        ),
    ]
