# Generated by Django 3.2.8 on 2022-11-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20221012_1607'),
        ('md', '0002_auto_20221013_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmdmeterapplication',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.customerprofile'),
        ),
        migrations.AddField(
            model_name='mdmeterapplication',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='md_meter_applications', to='accounts.customerprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmdmeterapplication',
            name='stage',
            field=models.CharField(choices=[('request_initiation', 'Request Initiation'), ('awaiting_approval', 'Awaiting Approval'), ('awaiting_inspection', 'Awaiting Inspection'), ('re_inspection_needed', 'Re-Inspection Needed'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], default='request_initiation', max_length=50),
        ),
        migrations.AlterField(
            model_name='mdmeterapplication',
            name='stage',
            field=models.CharField(choices=[('request_initiation', 'Request Initiation'), ('awaiting_approval', 'Awaiting Approval'), ('awaiting_inspection', 'Awaiting Inspection'), ('re_inspection_needed', 'Re-Inspection Needed'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], default='request_initiation', max_length=50),
        ),
    ]
