# Generated by Django 3.2.8 on 2022-11-07 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0003_auto_20221107_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmdmeterapplication',
            name='purpose_of_business',
            field=models.CharField(default='What is the purpose of Business', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmdmeterapplication',
            name='request_letter',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='mdmeterapplication',
            name='purpose_of_business',
            field=models.CharField(default='What is the purpose of Business', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdmeterapplication',
            name='request_letter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/md/request_letter', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
