# Generated by Django 3.2.8 on 2023-06-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20220927_1051'),
        ('md', '0004_auto_20221107_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmdmeterapplication',
            name='contractor_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalmdmeterapplication',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.region'),
        ),
        migrations.AddField(
            model_name='historicalmdmeterapplication',
            name='voltage_level',
            field=models.CharField(choices=[('11kva', '11KV'), ('33kva', '33KV')], default='11kva', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdmeterapplication',
            name='contractor_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mdmeterapplication',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='md_applications', to='location.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdmeterapplication',
            name='voltage_level',
            field=models.CharField(choices=[('11kva', '11KV'), ('33kva', '33KV')], default='11kva', max_length=5),
            preserve_default=False,
        ),
    ]
