# Generated by Django 3.2.8 on 2023-06-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20220927_1051'),
        ('md', '0005_auto_20230601_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdmeterapplication',
            options={'ordering': ('-updated', 'contractor', 'company_name'), 'verbose_name': 'MD Meter Application', 'verbose_name_plural': 'MD Meters Applications'},
        ),
        migrations.AlterField(
            model_name='historicalmdmeterapplication',
            name='voltage_level',
            field=models.CharField(blank=True, choices=[('11kva', '11KV'), ('33kva', '33KV')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mdmeterapplication',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='md_applications', to='location.region'),
        ),
        migrations.AlterField(
            model_name='mdmeterapplication',
            name='voltage_level',
            field=models.CharField(blank=True, choices=[('11kva', '11KV'), ('33kva', '33KV')], max_length=5, null=True),
        ),
    ]
