# Generated by Django 3.2.8 on 2023-08-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0007_historicalmdmeterapplicationinspection_historicalmdmeterapplicationtrxwindingcontinutytest_mdmeterap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmdmeterapplicationtrxwindingcontinutytest',
            old_name='B_R',
            new_name='b_n',
        ),
        migrations.RenameField(
            model_name='historicalmdmeterapplicationtrxwindingcontinutytest',
            old_name='R_Y',
            new_name='b_r',
        ),
        migrations.RenameField(
            model_name='historicalmdmeterapplicationtrxwindingcontinutytest',
            old_name='Y_B',
            new_name='r_n',
        ),
        migrations.RenameField(
            model_name='historicalmdmeterapplicationtrxwindingcontinutytest',
            old_name='b_n_small',
            new_name='r_y',
        ),
        migrations.RenameField(
            model_name='historicalmdmeterapplicationtrxwindingcontinutytest',
            old_name='r_n_small',
            new_name='y_b',
        ),
        migrations.RenameField(
            model_name='historicalmdmeterapplicationtrxwindingcontinutytest',
            old_name='y_n_small',
            new_name='y_n',
        ),
        migrations.RenameField(
            model_name='mdmeterapplicationtrxwindingcontinutytest',
            old_name='B_R',
            new_name='b_n',
        ),
        migrations.RenameField(
            model_name='mdmeterapplicationtrxwindingcontinutytest',
            old_name='R_Y',
            new_name='b_r',
        ),
        migrations.RenameField(
            model_name='mdmeterapplicationtrxwindingcontinutytest',
            old_name='Y_B',
            new_name='r_n',
        ),
        migrations.RenameField(
            model_name='mdmeterapplicationtrxwindingcontinutytest',
            old_name='b_n_small',
            new_name='r_y',
        ),
        migrations.RenameField(
            model_name='mdmeterapplicationtrxwindingcontinutytest',
            old_name='r_n_small',
            new_name='y_b',
        ),
        migrations.RenameField(
            model_name='mdmeterapplicationtrxwindingcontinutytest',
            old_name='y_n_small',
            new_name='y_n',
        ),
    ]
