# Generated by Django 3.2.8 on 2023-08-22 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_auto_20230316_1140'),
        ('md', '0008_auto_20230818_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDMeterApplicationTrxWindingInsulationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('hv_e', models.IntegerField(help_text='Reading in Giga Ohms')),
                ('lv_e', models.IntegerField(help_text='Reading in Giga Ohms')),
                ('hv_lv', models.IntegerField(help_text='Reading in Giga Ohms')),
                ('hv_e_dar', models.IntegerField(help_text='Dielectric Absorption Ratio')),
                ('lv_e_dar', models.IntegerField(help_text='Dielectric Absorption Ratio')),
                ('hv_lv_dar', models.IntegerField(help_text='Dielectric Absorption Ratio')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trx_insulation_test', to='md.mdmeterapplicationinspection')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'MD Meter TRX Winding Test Inspection',
                'verbose_name_plural': 'MD Meter TRX Winding Test Inspection',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalMDMeterApplicationTrxWindingInsulationTest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('hv_e', models.IntegerField(help_text='Reading in Giga Ohms')),
                ('lv_e', models.IntegerField(help_text='Reading in Giga Ohms')),
                ('hv_lv', models.IntegerField(help_text='Reading in Giga Ohms')),
                ('hv_e_dar', models.IntegerField(help_text='Dielectric Absorption Ratio')),
                ('lv_e_dar', models.IntegerField(help_text='Dielectric Absorption Ratio')),
                ('hv_lv_dar', models.IntegerField(help_text='Dielectric Absorption Ratio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='md.mdmeterapplicationinspection')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'historical MD Meter TRX Winding Test Inspection',
                'verbose_name_plural': 'historical MD Meter TRX Winding Test Inspection',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
