# Generated by Django 3.2.8 on 2022-02-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meters.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gridx', '0006_auto_20220109_1752'),
        ('meters', '0020_auto_20220214_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_alter_passwordresettokens_unique_together'),
        ('location', '0011_auto_20220104_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NMMPKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('first_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True, validators=[meters.models.checkAccountNumber])),
                ('bookcode', models.CharField(blank=True, max_length=10, null=True)),
                ('premises_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15)),
                ('customer_type', models.CharField(choices=[('new', 'New'), ('existing', 'existing'), ('separation', 'Separation'), ('replacement', 'Replacement')], max_length=15)),
                ('meter_number', models.CharField(blank=True, max_length=15, null=True)),
                ('band', models.CharField(choices=[('Band A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'))), ('Band B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'))), ('Band C', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('Band D', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'))), ('Band E', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5')))], max_length=15)),
                ('csp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.csp')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gridx.feeder')),
                ('kyc_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nmmp_kyc', to='accounts.userprofile')),
                ('meter_phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meters.meterphase')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.region')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gridx.transformer')),
            ],
            options={
                'verbose_name': 'NMMP KYC',
                'verbose_name_plural': 'NMMP KYCs',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNMMPKYC',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('first_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True, validators=[meters.models.checkAccountNumber])),
                ('bookcode', models.CharField(blank=True, max_length=10, null=True)),
                ('premises_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15)),
                ('customer_type', models.CharField(choices=[('new', 'New'), ('existing', 'existing'), ('separation', 'Separation'), ('replacement', 'Replacement')], max_length=15)),
                ('meter_number', models.CharField(blank=True, max_length=15, null=True)),
                ('band', models.CharField(choices=[('Band A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'))), ('Band B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'))), ('Band C', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('Band D', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'))), ('Band E', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5')))], max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('csp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.csp')),
                ('feeder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gridx.feeder')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kyc_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.userprofile')),
                ('meter_phase', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meters.meterphase')),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.region')),
                ('transformer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gridx.transformer')),
            ],
            options={
                'verbose_name': 'historical NMMP KYC',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
