# Generated by Django 3.2.8 on 2022-02-17 11:25

import core.utils.units
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnmmpkyc',
            name='uid',
            field=models.CharField(default=core.utils.units.genserial, max_length=10),
        ),
        migrations.AddField(
            model_name='nmmpkyc',
            name='uid',
            field=models.CharField(default=core.utils.units.genserial, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalnmmpkyc',
            name='customer_type',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('separation', 'Separation'), ('replacement', 'Replacement')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nmmpkyc',
            name='customer_type',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('separation', 'Separation'), ('replacement', 'Replacement')], max_length=15),
        ),
    ]
