# Generated by Django 3.2.8 on 2022-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmmp', '0002_auto_20220217_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnmmpkyc',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnmmpkyc',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nmmpkyc',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nmmpkyc',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
