# Generated by Django 3.2.8 on 2022-02-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_historicalvendor_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nmmp', '0003_auto_20220217_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnmmpkyc',
            name='premises_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('special', 'Special'), ('others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='nmmpkyc',
            name='premises_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('special', 'Special'), ('others', 'Others')], max_length=15),
        ),
        migrations.CreateModel(
            name='NMMPMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meter_number', models.CharField(max_length=15)),
                ('carton_number', models.CharField(max_length=15)),
                ('SGC', models.PositiveIntegerField()),
                ('FPU', models.FloatField(default=0)),
                ('assigned', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nmmp_meters', to='apps.vendor')),
            ],
            options={
                'verbose_name': 'NMMP Meter',
                'verbose_name_plural': 'NMMP Meters',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNMMPMeter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('meter_number', models.CharField(max_length=15)),
                ('carton_number', models.CharField(max_length=15)),
                ('SGC', models.PositiveIntegerField()),
                ('FPU', models.FloatField(default=0)),
                ('assigned', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.vendor')),
            ],
            options={
                'verbose_name': 'historical NMMP Meter',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
