# Generated by Django 3.2.8 on 2022-02-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0022_auto_20220217_1357'),
        ('nmmp', '0004_auto_20220217_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnmmpkyc',
            name='stage',
            field=models.CharField(choices=[('awaiting_meter', 'Awaiting Meter'), ('awaiting_capture', 'Awaiting Capture'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('completed', 'Completed')], default='awaiting_meter', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalnmmpmeter',
            name='kyc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nmmp.nmmpkyc'),
        ),
        migrations.AddField(
            model_name='historicalnmmpmeter',
            name='meter_phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meters.meterphase'),
        ),
        migrations.AddField(
            model_name='nmmpkyc',
            name='stage',
            field=models.CharField(choices=[('awaiting_meter', 'Awaiting Meter'), ('awaiting_capture', 'Awaiting Capture'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('completed', 'Completed')], default='awaiting_meter', max_length=50),
        ),
        migrations.AddField(
            model_name='nmmpmeter',
            name='kyc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter', to='nmmp.nmmpkyc'),
        ),
        migrations.AddField(
            model_name='nmmpmeter',
            name='meter_phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='meters.meterphase'),
            preserve_default=False,
        ),
    ]
