# Generated by Django 3.2.8 on 2022-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmmp', '0005_auto_20220217_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnmmpkyc',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nmmpkyc',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
