# Generated by Django 3.2.8 on 2022-03-03 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_alter_passwordresettokens_unique_together'),
        ('nmmp', '0006_auto_20220228_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='NMMPMeterInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('meter_number', models.CharField(max_length=15)),
                ('seal_number', models.CharField(blank=True, max_length=15, null=True)),
                ('SGC', models.PositiveIntegerField(default=999962, help_text='Vendor OLD SGC')),
                ('FPU', models.FloatField(default=0)),
                ('installation_date', models.DateField()),
                ('installed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nmmp_meters_installed', to='accounts.vendorprofile')),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installation', to='nmmp.nmmpkyc')),
            ],
            options={
                'verbose_name': 'NMMP Meter Installation',
                'verbose_name_plural': 'NMMP Meter Installations',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNMMPMeterInstallation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('meter_number', models.CharField(max_length=15)),
                ('seal_number', models.CharField(blank=True, max_length=15, null=True)),
                ('SGC', models.PositiveIntegerField(default=999962, help_text='Vendor OLD SGC')),
                ('FPU', models.FloatField(default=0)),
                ('installation_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('installed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.vendorprofile')),
                ('kyc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nmmp.nmmpkyc')),
            ],
            options={
                'verbose_name': 'historical NMMP Meter Installation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
