# Generated by Django 3.2.8 on 2022-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmmp', '0007_historicalnmmpmeterinstallation_nmmpmeterinstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnmmpkyc',
            name='email',
            field=models.EmailField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nmmpkyc',
            name='email',
            field=models.EmailField(blank=True, max_length=15, null=True),
        ),
    ]
