# Generated by Django 3.2.8 on 2022-03-11 09:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nmmp.utils
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0006_historicalvendor_vendor'),
        ('accounts', '0013_alter_passwordresettokens_unique_together'),
        ('nmmp', '0008_auto_20220303_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnmmpmeter',
            name='meter_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='nmmpmeter',
            name='meter_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='NMMPMeterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meters_file', models.FileField(upload_to=nmmp.utils.nmmp_meters_location, validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nmmp_meters_upload', to='accounts.vendorprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nmmp_meter_uploads', to='apps.vendor')),
            ],
            options={
                'verbose_name': 'NMMP Meter Upload',
                'verbose_name_plural': 'NMMP Meter Uploads',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNMMPMeterUpload',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('meters_file', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('upload_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.vendorprofile')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.vendor')),
            ],
            options={
                'verbose_name': 'historical NMMP Meter Upload',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
