# Generated by Django 3.2.8 on 2022-03-11 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meters', '0022_auto_20220217_1357'),
        ('nmmp', '0009_auto_20220311_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnmmpmeterupload',
            name='meter_phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meters.meterphase'),
        ),
        migrations.AddField(
            model_name='nmmpmeterupload',
            name='meter_phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='meters.meterphase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalnmmpmeterupload',
            name='upload_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nmmpmeterupload',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nmmp_meters_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
