# Generated by Django 3.2.8 on 2021-12-17 12:53

import core.utils.units
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20211217_1353'),
        ('location', '0006_alter_lga_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=core.utils.units.genserial, max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('meter_number', models.CharField(max_length=15)),
                ('stage', models.CharField(choices=[('awaiting_kyc', 'Awaiting KYC'), ('awaiting_payment', 'Awaiting Payment'), ('payment_approved', 'Payment Approved'), ('payment_approved', 'Payment Approved')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_applications', to='accounts.customerprofile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_applications', to='location.region')),
            ],
            options={
                'verbose_name': 'Meter Application',
                'verbose_name_plural': 'Meter Applications',
                'ordering': ['-updated'],
            },
        ),
    ]
