# Generated by Django 3.2.8 on 2021-12-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterapplication',
            name='meter_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='meterapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_kyc', 'Awaiting KYC'), ('complete_kyc', 'Complete KYC'), ('awaiting_payment', 'Awaiting Payment'), ('complete_payment', 'Complete Payment'), ('awaiting_installation', 'Awaiting Installation'), ('completed', 'completed')], max_length=50),
        ),
    ]
