# Generated by Django 3.2.8 on 2021-12-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211217_1353'),
        ('location', '0006_alter_lga_state'),
        ('meters', '0002_auto_20211217_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterApplicationKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('address', models.CharField(max_length=150)),
                ('meter_number', models.CharField(max_length=15)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kyc', to='meters.meterapplication')),
                ('csp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.csp')),
                ('kyc_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters_kyc', to='accounts.userprofile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.region')),
            ],
            options={
                'verbose_name': 'Meter Application KYC',
                'verbose_name_plural': 'Meter Applications KYC',
                'ordering': ['-updated'],
            },
        ),
    ]
