# Generated by Django 3.2.8 on 2021-12-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_auto_20211222_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterphase',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meterphase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
