# Generated by Django 3.2.8 on 2021-12-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0005_auto_20211223_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeterapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_kyc', 'Awaiting KYC'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_installation', 'Awaiting Installation'), ('completed', 'completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='meterapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_kyc', 'Awaiting KYC'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_installation', 'Awaiting Installation'), ('completed', 'completed')], max_length=50),
        ),
    ]
