# Generated by Django 3.2.8 on 2022-01-04 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customerprofile_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meters', '0007_auto_20211223_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalMeterApplicationIntallation',
            new_name='HistoricalMeterApplicationInstallation',
        ),
        migrations.RenameModel(
            old_name='MeterApplicationIntallation',
            new_name='MeterApplicationInstallation',
        ),
    ]
