# Generated by Django 3.2.8 on 2022-01-09 18:18

from django.db import migrations, models
import meters.models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0009_auto_20220105_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterapplicationkyc',
            name='account_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[meters.models.checkAccountNumber]),
        ),
        migrations.AddField(
            model_name='meterapplicationkyc',
            name='account_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[meters.models.checkAccountNumber]),
        ),
    ]
