# Generated by Django 3.2.8 on 2022-01-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0011_auto_20220115_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeterapplicationkyc',
            name='band',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meterapplicationkyc',
            name='band',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=15),
        ),
    ]
