# Generated by Django 3.2.8 on 2022-01-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0012_auto_20220118_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeterapplicationkyc',
            name='band',
            field=models.CharField(choices=[('Band A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'))), ('Band B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'))), ('unknown', 'Unknown')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meterapplicationkyc',
            name='band',
            field=models.CharField(choices=[('Band A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'))), ('Band B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'))), ('unknown', 'Unknown')], max_length=15),
        ),
    ]
