# Generated by Django 3.2.8 on 2022-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0013_auto_20220118_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeterapplicationkyc',
            name='band',
            field=models.CharField(choices=[('Band A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'))), ('Band B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'))), ('Band C', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('Band D', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'))), ('Band E', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5')))], max_length=15),
        ),
        migrations.AlterField(
            model_name='meterapplicationkyc',
            name='band',
            field=models.CharField(choices=[('Band A', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'))), ('Band B', (('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'))), ('Band C', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('Band D', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'))), ('Band E', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5')))], max_length=15),
        ),
    ]
