# Generated by Django 3.2.8 on 2022-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0014_auto_20220118_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterapplicationkyc',
            name='premises_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=15),
        ),
        migrations.AddField(
            model_name='meterapplicationkyc',
            name='premises_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalmeterapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_kyc', 'Awaiting KYC'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='meterapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_kyc', 'Awaiting KYC'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_installation', 'Awaiting Installation'), ('awaiting_account_generation', 'Awaiting Account Generation'), ('awaiting_capture', 'Awaiting Capture'), ('completed', 'Completed')], max_length=50),
        ),
    ]
