# Generated by Django 3.2.8 on 2022-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0017_auto_20220201_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterapplicationkyc',
            name='bookcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='meterapplicationkyc',
            name='bookcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
