# Generated by Django 3.2.8 on 2022-02-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0018_auto_20220203_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterapplicationkyc',
            name='customer_type',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'existing'), ('separation', 'Separation'), ('replacememt', 'Replacememt')], default='new', max_length=15),
        ),
        migrations.AddField(
            model_name='meterapplicationkyc',
            name='customer_type',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'existing'), ('separation', 'Separation'), ('replacememt', 'Replacememt')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalmeterapplication',
            name='request_type',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'existing'), ('separation', 'Separation'), ('replacememt', 'Replacememt')], default='new_request', max_length=20),
        ),
        migrations.AlterField(
            model_name='meterapplication',
            name='request_type',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'existing'), ('separation', 'Separation'), ('replacememt', 'Replacememt')], default='new_request', max_length=20),
        ),
    ]
