# Generated by Django 3.2.8 on 2022-02-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0021_auto_20220217_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeterapplicationkyc',
            name='premises_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('special', 'Special'), ('others', 'Others')], default='residential', max_length=15),
        ),
        migrations.AlterField(
            model_name='meterapplicationkyc',
            name='premises_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('special', 'Special'), ('others', 'Others')], default='residential', max_length=15),
        ),
    ]
