# Generated by Django 3.2.8 on 2022-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0022_auto_20220217_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterapplicationinstallation',
            name='nimsa_seal_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='meterapplicationinstallation',
            name='nimsa_seal_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
