# Generated by Django 3.2.8 on 2022-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0023_auto_20220610_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmeterapplication',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Meter Application', 'verbose_name_plural': 'historical Meter Applications'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeterapplicationinstallation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Meter Application Installation', 'verbose_name_plural': 'historical Meter Applications Installations'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeterapplicationkyc',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Meter Application KYC', 'verbose_name_plural': 'historical Meter Applications KYC'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeterapplicationpayment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Meter Application Payment', 'verbose_name_plural': 'historical Meter Applications Payments'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeterphase',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Meter Phase', 'verbose_name_plural': 'historical Meter Phases'},
        ),
        migrations.AlterField(
            model_name='historicalmeterapplication',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmeterapplicationinstallation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmeterapplicationkyc',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmeterapplicationpayment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmeterphase',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
