# Generated by Django 3.2.8 on 2021-10-07 10:24

import core.utils.units
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userprofile_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('uid', models.UUIDField(default=core.utils.units.LongUniqueId, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SDS Application',
                'verbose_name_plural': 'SDS Applications',
                'ordering': ['-updated', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserAppPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('privileges', models.JSONField()),
                ('access_status', models.BooleanField(default=True)),
                ('app', models.ForeignKey(limit_choices_to=models.Q(('active', True)), on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apps.application')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_privileges', to='accounts.userprofile')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usertype')),
            ],
            options={
                'verbose_name': 'User Application Privilege',
                'verbose_name_plural': 'User Applications Privileges',
                'ordering': ['-updated', 'app'],
                'unique_together': {('app', 'profile')},
            },
        ),
    ]
