# Generated by Django 3.2.8 on 2021-12-20 14:50

import core.utils.units
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211010_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='uid',
            field=models.UUIDField(default=core.utils.units.LongUniqueId, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='uid',
            field=models.UUIDField(db_index=True, default=core.utils.units.LongUniqueId, editable=False),
        ),
    ]
