# Generated by Django 3.2.8 on 2022-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_historicalvendor_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalapplication',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical SDS Application', 'verbose_name_plural': 'historical SDS Applications'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserappprivilege',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical User Application Privilege', 'verbose_name_plural': 'historical User Applications Privileges'},
        ),
        migrations.AlterModelOptions(
            name='historicalvendor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vendor', 'verbose_name_plural': 'historical Vendors'},
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluserappprivilege',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
